## Lecture des donn√©es

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('./data/Video_Games_Sales_as_at_22_Dec_2016.csv')
data.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
data['User_Score'] = data['User_Score'].replace('tbd', np.nan)

## Valeurs manquantes

In [4]:
# M√©thode pour calculer le nombre de valeurs manquantes pour chaque variable explicative
def valeursManquantes(df):
        valeurs = df.isnull().sum()
        valeursPourcent = 100 * df.isnull().sum() / len(df)
        table = pd.concat([valeurs, valeursPourcent], axis=1)
        
        # On rennomme les colonnes
        tableRenommer = table.rename(columns = {0 : "Valeurs Manquantes", 1 : "% des valeurs totales"})
        tableRenommer = tableRenommer[tableRenommer.iloc[:,1] != 0].sort_values("% des valeurs totales", ascending=False).round(1)
        
        return tableRenommer

valeursManquantes(data)

                 Valeurs Manquantes  % des valeurs totales
User_Score                     9129                   54.6
User_Count                     9129                   54.6
Critic_Score                   8582                   51.3
Critic_Count                   8582                   51.3
Rating                         6769                   40.5
Developer                      6623                   39.6
Year_of_Release                 269                    1.6
Publisher                        54                    0.3
Name                              2                    0.0
Genre                             2                    0.0

In [5]:
User_Count = pd.DataFrame()
User_Count['User_Count'] = data['User_Count']

User_Count_mode = User_Count.mode().values[0,0]

data = data.fillna({'User_Count':User_Count_mode})

In [6]:
Critic_Score = pd.DataFrame()
Critic_Score['Critic_Score'] = data['Critic_Score']

Critic_Score_mode = Critic_Score.mode().values[0,0]

data = data.fillna({'Critic_Score': Critic_Score_mode})

In [7]:
Critic_Count = pd.DataFrame()
Critic_Count['Critic_Count'] = data['Critic_Count']

Critic_Count_mode = Critic_Count.mode().values[0,0]

data = data.fillna({'Critic_Count': Critic_Count_mode})

In [8]:
Rating = pd.DataFrame()
Rating['Rating'] = data['Rating']

Rating_mode = Rating.mode().values[0,0]

data = data.fillna({'Rating': Rating_mode})

In [9]:
User_Score = pd.DataFrame()
User_Score['User_Score'] = data['User_Score']

User_Score_mode = User_Score.mode().values[0,0]

data = data.fillna({'User_Score': User_Score_mode})

In [10]:
Developer = pd.DataFrame()
Developer['Developer'] = data['Developer']

Developer_mode = Developer.mode().values[0,0]

data = data.fillna({'Developer': Developer_mode})

In [11]:
Year_of_Release = pd.DataFrame()
Year_of_Release['Year_of_Release'] = data['Year_of_Release']

Year_of_Release_mode = Year_of_Release.mode().values[0,0]

data = data.fillna({'Year_of_Release': Year_of_Release_mode})

In [12]:
Publisher = pd.DataFrame()
Publisher['Publisher'] = data['Publisher']

Publisher_mode = Publisher.mode().values[0,0]

data = data.fillna({'Publisher': Publisher_mode})

In [13]:
Genre = pd.DataFrame()
Genre['Genre'] = data['Genre']

Genre_mode = Genre.mode().values[0,0]

data = data.fillna({'Genre': Genre_mode})

In [14]:
valeursManquantes(data)

      Valeurs Manquantes  % des valeurs totales
Name                   2                    0.0

In [15]:
data.dropna()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,70.0,4.0,7.8,4.0,Ubisoft,E
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,70.0,4.0,7.8,4.0,Ubisoft,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16714,Samurai Warriors: Sanada Maru,PS3,2016.0,Action,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,70.0,4.0,7.8,4.0,Ubisoft,E
16715,LMA Manager 2007,X360,2006.0,Sports,Codemasters,0.00,0.01,0.00,0.00,0.01,70.0,4.0,7.8,4.0,Ubisoft,E
16716,Haitaka no Psychedelica,PSV,2016.0,Adventure,Idea Factory,0.00,0.00,0.01,0.00,0.01,70.0,4.0,7.8,4.0,Ubisoft,E
16717,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,70.0,4.0,7.8,4.0,Ubisoft,E
16718,Winning Post 8 2016,PSV,2016.0,Simulation,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,70.0,4.0,7.8,4.0,Ubisoft,E

In [16]:
data.to_csv("./data/videogames.csv", index=False)

## Label Encoding

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
encoder = LabelEncoder()

new_column_platform = encoder.fit_transform(data["Platform"].values)
new_column_genre = encoder.fit_transform(data["Genre"].values)
new_column_publisher = encoder.fit_transform(data["Publisher"].values)
new_column_developer = encoder.fit_transform(data["Developer"].values)
new_column_rating = encoder.fit_transform(data["Rating"].values)

encoded_data = data.copy()

encoded_data["Platform"] = new_column_platform
encoded_data["Genre"] = new_column_genre
encoded_data["Publisher"] = new_column_publisher
encoded_data["Developer"] = new_column_developer
encoded_data["Rating"] = new_column_rating

encoded_data.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,26,2006.0,10,361,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,1020,1
1,Super Mario Bros.,11,1985.0,4,361,29.08,3.58,6.81,0.77,40.24,70.0,4.0,7.8,4.0,1539,1
2,Mario Kart Wii,26,2008.0,6,361,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,1020,1
3,Wii Sports Resort,26,2009.0,10,361,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,1020,1
4,Pokemon Red/Pokemon Blue,5,1996.0,7,361,11.27,8.89,10.22,1.00,31.37,70.0,4.0,7.8,4.0,1539,1

In [19]:
y = encoded_data['Global_Sales']
encoded_data = encoded_data.drop(columns=['Global_Sales', 'Name'])

encoded_data_1 = encoded_data.drop(columns=['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales'])
X1 = encoded_data_1.to_numpy()
encoded_data_2 = encoded_data.drop(columns=['Platform', 'Year_of_Release', 'Genre', 'Publisher', 'Critic_Score', 'Critic_Count', 'User_Score', 'User_Count', 'Developer', 'Rating'])
X2 = encoded_data_2.to_numpy()

## MinMaxScaler

In [20]:
from  sklearn.preprocessing import MinMaxScaler

In [21]:
X1 = MinMaxScaler().fit_transform(X1)
X2 = MinMaxScaler().fit_transform(X2)

## Linear Reg

In [22]:
from sklearn.linear_model import LinearRegression

In [23]:
reg1 = LinearRegression().fit(X1, y)
reg2 = LinearRegression().fit(X2, y)

In [24]:
weights1 = reg1.coef_
weights1 = (weights1 - np.min(weights1))/np.ptp(weights1)

weights2 = reg2.coef_
weights2 = (weights2 - np.min(weights2))/np.ptp(weights2)

In [25]:
columns1 = encoded_data_1.columns

columns2 = encoded_data_2.columns

In [26]:
d1 = {'columns': columns1, 'weights': weights1}
d2 = {'columns': columns2, 'weights': weights2}
df1 = pd.DataFrame(data=d1)
df2 = pd.DataFrame(data=d2)

print(df1)
print(df2)

           columns   weights
0         Platform  0.177051
1  Year_of_Release  0.000000
2            Genre  0.165987
3        Publisher  0.179465
4     Critic_Score  0.365360
5     Critic_Count  0.468131
6       User_Score  0.099335
7       User_Count  1.000000
8        Developer  0.191765
9           Rating  0.120953
       columns   weights
0     NA_Sales  1.000000
1     EU_Sales  0.601877
2     JP_Sales  0.000000
3  Other_Sales  0.011109

In [ ]:
df1.to_csv('./data/weights_nonsale.csv', index=False)
df2.to_csv('./data/weights_sale.csv', index=False)